# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    pdf_directory: '%kernel.project_dir%/public/uploads/pdfs%'
    api_key: '%env(GSK_API_KEY)%' # <-- your Groq API key

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available as services
    App\:
        resource: '../src/'

    # explicit service definition
    App\Service\AiDescriptionService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'